'use client';

import React, { useState } from 'react';
import { Download, Printer, FileText } from 'lucide-react';
import jsPDF from 'jspdf';

interface PDFReportViewProps {
  attempt: {
    id?: string;
    attemptId?: string;
    mode?: string;
    startedAt: string;
    submittedAt: string | null;
    timeSpentSeconds?: number;
    durationSeconds?: number;
    passed: boolean;
    scoredCorrect?: number;
    scoredIncorrect?: number;
    unscoredCorrect?: number;
    unscoredIncorrect?: number;
    totalCorrect?: number;
    scorePercentage?: number;
    proctoringClean?: boolean;
    violationCount?: number;
  };
  summary: {
    scoredScore: number;
    totalScored: number;
    unscoredScore: number;
    totalUnscored: number;
    totalCorrect: number;
    totalQuestions: number;
    percentage: number;
    passed: boolean;
    domainBreakdown: Record<string, { total: number; correct: number; percentage: number }>;
  };
  questions: Array<{
    position: number;
    questionCode: string;
    questionText: string;
    domain: string;
    topic: string;
    isScored: boolean;
    isCorrect: boolean;
    correctAnswers: string[];
    selectedOptions: string[];
    explanation: string;
    sourceModule?: string;
    options?: Array<{ label: string; text: string; isCorrect: boolean }>;
  }>;
}

export function PDFReportView({ attempt, summary, questions }: PDFReportViewProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [isGeneratingReview, setIsGeneratingReview] = useState(false);

  const formatDuration = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}m ${secs}s`;
  };

  // Helper: add new page header
  const addPageHeader = (doc: jsPDF, pageNum: number, totalPages?: number) => {
    const pageWidth = doc.internal.pageSize.getWidth();
    doc.setFillColor(11, 15, 25);
    doc.rect(0, 0, pageWidth, 12, 'F');
    doc.setFillColor(255, 153, 0);
    doc.rect(0, 12, pageWidth, 1.5, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(203, 213, 225);
    doc.text('CloudPrep — AWS CLF-C02 Full Question Review', 14, 9);
    doc.setTextColor(100, 116, 139);
    doc.text(`Page ${pageNum}`, pageWidth - 25, 9);
  };

  // Helper: add page footer
  const addPageFooter = (doc: jsPDF, pageNum: number) => {
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setDrawColor(51, 65, 85);
    doc.line(14, pageHeight - 10, pageWidth - 14, pageHeight - 10);
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text('Generated by CloudPrep — AWS Certified Cloud Practitioner Practice & Proctored Examination System.', 14, pageHeight - 6);
  };

  const handleDownloadPDF = () => {
    try {
      setIsGenerating(true);
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      const pageWidth = doc.internal.pageSize.getWidth();
      let y = 18;

      // Header Banner
      doc.setFillColor(11, 15, 25);
      doc.rect(0, 0, pageWidth, 36, 'F');
      doc.setFillColor(255, 153, 0);
      doc.rect(0, 36, pageWidth, 2.5, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(18);
      doc.text('CloudPrep — AWS Certification Practice Report', 14, 16);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(203, 213, 225);
      doc.text('AWS Certified Cloud Practitioner (CLF-C02) • Official Examination Audit', 14, 24);
      const examDate = new Date(attempt.startedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
      const attemptIdStr = attempt.id || attempt.attemptId || 'UNKNOWN';
      const duration = attempt.timeSpentSeconds || attempt.durationSeconds || 0;
      doc.setFontSize(9);
      doc.setTextColor(148, 163, 184);
      doc.text(`Exam ID: ${attemptIdStr.substring(0, 16)}... | Date: ${examDate} | Time: ${formatDuration(duration)}`, 14, 31);
      y = 48;

      // Result Status
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      if (summary.passed) {
        doc.setFillColor(16, 185, 129, 0.15);
        doc.setDrawColor(16, 185, 129);
        doc.roundedRect(14, y, pageWidth - 28, 24, 3, 3, 'FD');
        doc.setTextColor(16, 185, 129);
        doc.text('RESULT: PASSED', 20, y + 10);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(30, 41, 59);
        doc.text(`Scored: ${summary.scoredScore} / ${summary.totalScored} (${summary.percentage}%) — Minimum 35/50 (70%) to pass.`, 20, y + 18);
      } else {
        doc.setFillColor(239, 68, 68, 0.15);
        doc.setDrawColor(239, 68, 68);
        doc.roundedRect(14, y, pageWidth - 28, 24, 3, 3, 'FD');
        doc.setTextColor(239, 68, 68);
        doc.text('RESULT: DID NOT PASS', 20, y + 10);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(30, 41, 59);
        doc.text(`Scored: ${summary.scoredScore} / ${summary.totalScored} (${summary.percentage}%) — Minimum 35/50 (70%) to pass.`, 20, y + 18);
      }
      y += 32;

      // Stats Grid
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(15, 23, 42);
      doc.text('EXAM PERFORMANCE METRICS', 14, y);
      y += 5;
      doc.setDrawColor(226, 232, 240);
      doc.setFillColor(248, 250, 252);
      doc.rect(14, y, pageWidth - 28, 28, 'FD');
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.text('Scored Questions', 20, y + 8);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(15, 23, 42);
      doc.text(`${summary.scoredScore} / ${summary.totalScored}`, 20, y + 18);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.text('Unscored Questions', 65, y + 8);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(15, 23, 42);
      doc.text(`${summary.unscoredScore} / ${summary.totalUnscored}`, 65, y + 18);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.text('Total Correct', 115, y + 8);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(15, 23, 42);
      doc.text(`${summary.totalCorrect} / ${summary.totalQuestions}`, 115, y + 18);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.text('Proctoring Integrity', 155, y + 8);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      if (attempt.violationCount === 0) {
        doc.setTextColor(16, 185, 129);
        doc.text('Verified Clean', 155, y + 18);
      } else {
        doc.setTextColor(239, 68, 68);
        doc.text(`${attempt.violationCount} Violations`, 155, y + 18);
      }
      y += 36;

      // Domain Breakdown
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(15, 23, 42);
      doc.text('CLF-C02 DOMAIN BREAKDOWN', 14, y);
      y += 6;
      const domains = Object.entries(summary.domainBreakdown);
      domains.forEach(([domainName, data]) => {
        doc.setDrawColor(226, 232, 240);
        doc.line(14, y, pageWidth - 14, y);
        y += 5;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(15, 23, 42);
        doc.text(domainName, 16, y);
        const domainResult = `${data.correct}/${data.total} (${data.percentage}%)`;
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(data.percentage >= 70 ? 16 : 225, data.percentage >= 70 ? 185 : 29, data.percentage >= 70 ? 129 : 72);
        doc.text(domainResult, pageWidth - 45, y);
        y += 4;
      });

      y += 10;
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text('Generated by CloudPrep — AWS Certified Cloud Practitioner Practice & Proctored Examination System.', 14, y);

      const pdfId = attempt.id || attempt.attemptId || 'UNKNOWN';
      doc.save(`CloudPrep_ScoreReport_${pdfId.substring(0, 8)}.pdf`);
    } catch (err) {
      console.error('Failed to generate PDF:', err);
      alert('Could not generate PDF. You can also use Print to save as PDF.');
    } finally {
      setIsGenerating(false);
    }
  };

  // Full question-by-question review PDF
  const handleDownloadFullReview = () => {
    try {
      setIsGeneratingReview(true);
      const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const marginL = 14;
      const marginR = pageWidth - 14;
      const contentWidth = marginR - marginL;
      let y = 20;
      let pageNum = 1;

      const checkNewPage = (neededHeight: number) => {
        if (y + neededHeight > pageHeight - 14) {
          addPageFooter(doc, pageNum);
          doc.addPage();
          pageNum++;
          addPageHeader(doc, pageNum);
          y = 20; // below top header banner (height 12mm + gap)
        }
      };

      // ── Cover Page ──────────────────────────────────────────
      doc.setFillColor(11, 15, 25);
      doc.rect(0, 0, pageWidth, pageHeight, 'F');
      doc.setFillColor(255, 153, 0);
      doc.rect(0, 60, pageWidth, 3, 'F');
      doc.rect(0, pageHeight - 3, pageWidth, 3, 'F');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(28);
      doc.setTextColor(255, 255, 255);
      doc.text('CloudPrep', marginL, 48);

      doc.setFontSize(13);
      doc.setTextColor(255, 153, 0);
      doc.text('AWS Certified Cloud Practitioner (CLF-C02)', marginL, 58);

      doc.setFontSize(22);
      doc.setTextColor(255, 255, 255);
      doc.text('Full Attempt Review', marginL, 80);
      doc.text('Question-by-Question Analysis', marginL, 92);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      doc.setTextColor(148, 163, 184);
      const examDate = new Date(attempt.startedAt).toLocaleString();
      const attemptIdStr = attempt.id || attempt.attemptId || 'UNKNOWN';
      doc.text(`Exam Date: ${examDate}`, marginL, 112);
      doc.text(`Attempt ID: ${attemptIdStr}`, marginL, 120);
      doc.text(`Total Questions: ${questions.length}`, marginL, 128);

      // Score box
      doc.setDrawColor(summary.passed ? 16 : 239, summary.passed ? 185 : 68, summary.passed ? 129 : 68);
      doc.setFillColor(summary.passed ? 16 : 239, summary.passed ? 185 : 68, summary.passed ? 129 : 68, 0.1);
      doc.roundedRect(marginL, 140, contentWidth, 30, 3, 3, 'FD');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.setTextColor(summary.passed ? 16 : 239, summary.passed ? 185 : 68, summary.passed ? 129 : 68);
      doc.text(summary.passed ? '✓ PASSED' : '✗ DID NOT PASS', marginL + 6, 152);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(11);
      doc.setTextColor(200, 210, 220);
      doc.text(`Score: ${summary.scoredScore} / ${summary.totalScored} (${summary.percentage}%) | Correct: ${summary.totalCorrect} / ${summary.totalQuestions}`, marginL + 6, 163);

      doc.setFont('helvetica', 'italic');
      doc.setFontSize(8);
      doc.setTextColor(71, 85, 105);
      doc.text('Generated by CloudPrep — AWS Certified Cloud Practitioner Practice & Proctored Examination System.', marginL, pageHeight - 10);

      // ── Question Review Pages ─────────────────────────────────
      doc.addPage();
      pageNum++;
      addPageHeader(doc, pageNum);
      y = 20;

      // Section header
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(15, 23, 42);
      doc.text('FULL QUESTION REVIEW', marginL, y);
      y += 3;
      doc.setDrawColor(255, 153, 0);
      doc.setLineWidth(0.8);
      doc.line(marginL, y, marginL + 60, y);
      doc.setLineWidth(0.2);
      y += 6;

      questions.forEach((q, idx) => {
        const isCorrect = q.isCorrect;
        const userSelected = q.selectedOptions || [];
        const correctAns = q.correctAnswers || [];

        // Check if question header + question text fits on page, else break before question
        const questionTextLines = doc.splitTextToSize(q.questionText || '(No question text)', contentWidth - 4);
        const qHeaderAndTextHeight = 8 + 3 + (questionTextLines.length * 4.5) + 3;
        checkNewPage(qHeaderAndTextHeight + 12); // ensure header and at least first option can fit

        // Question number badge + status bar
        const badgeColor: [number, number, number] = isCorrect ? [16, 185, 129] : (userSelected.length === 0 ? [100, 116, 139] : [239, 68, 68]);
        doc.setFillColor(...badgeColor);
        doc.roundedRect(marginL, y, contentWidth, 7, 1.2, 1.2, 'F');

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        doc.setTextColor(255, 255, 255);
        const statusLabel = userSelected.length === 0 ? 'SKIPPED' : (isCorrect ? 'CORRECT' : 'INCORRECT');
        doc.text(`Q${q.position}  •  ${statusLabel}  •  ${q.domain || ''}  •  ${q.isScored ? 'Scored' : 'Unscored'}`, marginL + 3, y + 4.8);
        y += 9;

        // Question text
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8.5);
        doc.setTextColor(15, 23, 42);
        doc.text(questionTextLines, marginL + 2, y);
        y += questionTextLines.length * 4.5 + 3;

        // Options
        const opts = q.options || correctAns.map(l => ({ label: l, text: l, isCorrect: true }));
        opts.forEach((opt) => {
          const isUserChoice = userSelected.includes(opt.label);
          const isCorrectOpt = q.correctAnswers.includes(opt.label);

          let bgR = 248, bgG = 250, bgB = 252;
          let borderR = 226, borderG = 232, borderB = 240;
          let textR = 51, textG = 65, textB = 85;

          if (isCorrectOpt) {
            bgR = 240; bgG = 253; bgB = 244;
            borderR = 16; borderG = 185; borderB = 129;
            textR = 6; textG = 95; textB = 70;
          }
          if (isUserChoice && !isCorrectOpt) {
            bgR = 254; bgG = 242; bgB = 242;
            borderR = 239; borderG = 68; borderB = 68;
            textR = 153; textG = 27; textB = 27;
          }

          // Reserve 30mm on right for labels if present, 16mm left for circle
          const hasLabel = isCorrectOpt || isUserChoice;
          const labelReserve = hasLabel ? 32 : 6;
          const optTextWidth = contentWidth - 16 - labelReserve;
          doc.setFontSize(8);
          const optLines = doc.splitTextToSize(opt.text || '', optTextWidth);
          const optHeight = Math.max(7.5, optLines.length * 4 + 3.5);
          checkNewPage(optHeight + 1.5);

          doc.setFillColor(bgR, bgG, bgB);
          doc.setDrawColor(borderR, borderG, borderB);
          doc.setLineWidth(0.35);
          doc.roundedRect(marginL + 2, y, contentWidth - 4, optHeight, 1, 1, 'FD');
          doc.setLineWidth(0.2);

          // Letter bubble
          doc.setFillColor(borderR, borderG, borderB);
          doc.circle(marginL + 6.5, y + optHeight / 2, 2.8, 'F');
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(7);
          doc.setTextColor(255, 255, 255);
          doc.text(opt.label, marginL + 5.3, y + optHeight / 2 + 2);

          // Option text
          doc.setFont('helvetica', isUserChoice || isCorrectOpt ? 'bold' : 'normal');
          doc.setFontSize(7.8);
          doc.setTextColor(textR, textG, textB);
          const textStartY = y + 3.5;
          doc.text(optLines, marginL + 12, textStartY);

          // Right-side label
          const rightX = marginR - 4;
          const midY = y + optHeight / 2 + 1.8;
          if (isCorrectOpt && isUserChoice) {
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(6.5);
            doc.setTextColor(16, 185, 129);
            doc.text('✓ YOUR ANSWER', rightX, midY, { align: 'right' });
          } else if (isCorrectOpt) {
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(6.5);
            doc.setTextColor(16, 185, 129);
            doc.text('✓ CORRECT', rightX, midY, { align: 'right' });
          } else if (isUserChoice) {
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(6.5);
            doc.setTextColor(239, 68, 68);
            doc.text('✗ YOUR ANSWER', rightX, midY, { align: 'right' });
          }

          y += optHeight + 1.5;
        });

        // Summary annotation for wrong answers
        if (!isCorrect && userSelected.length > 0) {
          checkNewPage(9);
          doc.setFillColor(255, 251, 235);
          doc.setDrawColor(245, 158, 11);
          doc.roundedRect(marginL + 2, y, contentWidth - 4, 7.5, 1, 1, 'FD');
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(7.5);
          doc.setTextColor(92, 53, 0);
          doc.text(`You answered: ${userSelected.join(', ')}   |   Correct answer: ${correctAns.join(', ')}`, marginL + 5, y + 5);
          y += 9.5;
        }

        // Explanation
        if (q.explanation && q.explanation !== 'No explanation provided.') {
          const expLines = doc.splitTextToSize(`Explanation: ${q.explanation}`, contentWidth - 10);
          checkNewPage(expLines.length * 4.5 + 6);
          doc.setFillColor(239, 246, 255);
          doc.setDrawColor(99, 102, 241);
          doc.roundedRect(marginL + 2, y, contentWidth - 4, expLines.length * 4.5 + 4, 1, 1, 'FD');
          doc.setFont('helvetica', 'italic');
          doc.setFontSize(7.5);
          doc.setTextColor(55, 48, 163);
          doc.text(expLines, marginL + 5, y + 4);
          y += expLines.length * 4.5 + 6;
        }

        y += 6;

        // Divider
        if (idx < questions.length - 1) {
          checkNewPage(4);
          doc.setDrawColor(226, 232, 240);
          doc.setLineWidth(0.3);
          doc.line(marginL, y, marginR, y);
          doc.setLineWidth(0.2);
          y += 4;
        }
      });

      addPageFooter(doc, pageNum);

      const pdfId = attempt.id || attempt.attemptId || 'UNKNOWN';
      doc.save(`CloudPrep_FullReview_${pdfId.substring(0, 8)}.pdf`);
    } catch (err) {
      console.error('Failed to generate full review PDF:', err);
      alert('Could not generate PDF. Please try again.');
    } finally {
      setIsGeneratingReview(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="flex flex-wrap items-center gap-3">
      <button
        onClick={handleDownloadPDF}
        disabled={isGenerating}
        className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-400 hover:to-amber-500 text-slate-950 font-bold text-xs shadow-lg shadow-amber-500/20 hover:shadow-amber-500/30 transition-all hover:scale-105 active:scale-95 disabled:opacity-50"
      >
        <FileText className="w-4 h-4 stroke-[2.5]" />
        <span>{isGenerating ? 'Generating...' : 'Score Report (PDF)'}</span>
      </button>

      <button
        onClick={handleDownloadFullReview}
        disabled={isGeneratingReview}
        className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-indigo-600 to-indigo-700 hover:from-indigo-500 hover:to-indigo-600 text-white font-bold text-xs shadow-lg shadow-indigo-500/20 hover:shadow-indigo-500/30 transition-all hover:scale-105 active:scale-95 disabled:opacity-50"
      >
        <Download className="w-4 h-4 stroke-[2.5]" />
        <span>{isGeneratingReview ? 'Building Full Review...' : 'Full Question Review (PDF)'}</span>
      </button>

      <button
        onClick={handlePrint}
        className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 font-semibold text-xs transition-all hover:scale-105"
      >
        <Printer className="w-4 h-4" />
        <span>Print</span>
      </button>
    </div>
  );
}
